### ISSUE TITLE
Unknown file extension

### ISSUE THREAD

**Issue by ali-tafakkori** [vladmandic/face-api#10]
hi
I can not use it in ubuntu

Error [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension: /home/ali/Desktop/Nodejs%20Projects/face-api-test/node_modules/@vladmandic/face-api/dist/face-api.cjs
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:93:13)
    at Loader.resolve (internal/modules/esm/loader.js:58:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:113:40)
    at ModuleWrap.promises.module.link (internal/modules/esm/module_job.js:32:40)
    at link (internal/modules/esm/module_job.js:31:36)

**Comment by vladmandic** [comment]
`cjs` is common way to describe that `js` module is in commonjs format, surpised that something does not recognize it

- what is the environment (nodejs or browser)?
- which version of node?
- are you using any packager (rollup, webpack, browserify, etc.)?
- can you share your `package.json`
- how are you importing `face-api` - please share the code  
  (e.g. `const faceapi = require(@vladmandic/faceapi) or `import ... ` or something else)

can you try to rename `@vladmandic/face-api/dist/face-api.cjs` to `@vladmandic/face-api/dist/face-api.node.js`  
and then import/require that explicit file instead of just module name?

**Comment by vladmandic** [comment]
this seems to be a `webpack` compatibility issue as it doesn't recognize `cjs` extension as valid `js` input although it's pretty common.

i've updated the build process to produce `dist/face-api.node.js` instead of `dist/face-api.cjs` and set it as default import.

this should resolve the problem, let me know if it works.

**Comment by vladmandic** [comment]
@ali-tafakkori any updates?

**Comment by ali-tafakkori** [comment]
Sorry I answered late.
It fixed now.
Thanks
