### ISSUE TITLE
Question - yes/no - JavaScript without polyfills

### ISSUE THREAD

**Issue by meeki007** [vladmandic/face-api#11]
You state: "Typescript build process now targets ES2018 and instead of dual ES5/ES6
Resulting code is clean ES2018 JavaScript without polyfills"

So I no longer have to use the monkeyPatch?
```
// patch nodejs environment, we need to provide an implementation of
// HTMLCanvasElement and HTMLImageElement
const { Canvas, Image, ImageData } = canvas
faceapi.env.monkeyPatch({ Canvas, Image, ImageData })
```
If so that would be great to loose the canvas depends that has been giving me trouble of late. 

thank you,
meeki007

**Comment by vladmandic** [comment]
version of ECMAScript used is not related to canvas  

`monkeypatch` is needed when running in `nodejs` instead of `browser` since `nodejs` does not have canvas implementation on its own. adding `canvas` here is not just a polyfill, it's full implemention of canvas for nodejs.

now, if you provide `imagedata` as input yourself and don't rely on any of the helper methods that actually draw detected results and parse results yourself, it *might* work without canvas.

i haven't tried it, but i'd be willing to help.

**Comment by meeki007** [comment]
Thanks for the clarification. I'll look into it. I rather like what you have done to make this fork as modular as possible. I'd rather not add bloat to the code when canvas does the job.

What I would love todo and plan to do is write up a bunch of documentation examples of working with it in nodeJS / node-red once I make the migration to your package.

Thanks again!
QUESTION SOLVED!
Closing issue.
