### ISSUE TITLE
node-cpu build not available

### ISSUE THREAD

**Issue by LeoMartinDev** [vladmandic/face-api#124]
Hi !
Looking at the documentation, we should be able to use `face-api.node-cpu` build but it looks like it has been removed in this commit https://github.com/vladmandic/face-api/commit/d13586f54980b7ad14744b9c2ee260e9b573ada7

> If you want to use FaceAPI in a NodeJS on platforms where NodeJS binary libraries are not supported, you can use JavaScript CPU backend.
  npm install @tensorflow/tfjs
  npm install @vladmandic/face-api 
And then use with:
  const tf = require('@tensorflow/tfjs')
  const faceapi = require('@vladmandic/face-api/dist/face-api.node-cpu.js');

Any way to solve this issue ?

**Comment by vladmandic** [comment]
i forgot to remove it from readme  

but the target was removed because:
- there was no demand or use-case for it
- non-accelerated js code is too slow for anything except proof-of-concept

if you cannot use native tensorflow (via `tfjs-node` or `tfjs-node-gpu`) because you're on unsupported platform,  
you use `face-api.node-wasm.js` as that is still cross-platform and far faster than `node-cpu` would be  

what is your use case?

**Comment by LeoMartinDev** [comment]
I'm trying to run face-api in a Vercel lambda function.
My issue is that there is a bundle size limit per function of 50Mb and thanks to tensorflow, my build size is over 150Mb 😬

**Comment by vladmandic** [comment]
closing as resolved, but feel free to post any additional questions here.
