### ISSUE TITLE
Pitch and yaw values aren't correct. 

### ISSUE THREAD

**Issue by TheSohaibAhmed** [vladmandic/face-api#128]
**Issue Description**
The yaw and pitch values are somewhat problematic (understandably). Somehow yaw remains in negative, and pitch changes as you shake your head (but don't actually tilt your head forwards or backwards).

**Steps to Reproduce**
You can see this on the demo too: Keep your head straight; look to the left, and then to the right without pitching your head -- watch the pitch values change. 

**Expected Behavior**
Maybe if there was someway to make it more consistent? 

**Environment
On the demo itself

**Additional**
Some thoughts re. yaw : Have you maybe considered measuring the ear-to-ear and ear-to-nose (X2) distances? Because if let's say the right ear to nose distance is shorter then we know we'd be looking to one side. 

PS. Sorry for not a a lot of info on the system -- I noticed that the issue showed up in the demo and was consistent with my build and across browsers so I figured that it's maybe a universal problem? Let me know if I'm wrong or can help you fix this in anyway

**Comment by vladmandic** [comment]
if you're interested, feel free to contribute to `@vladmandic/face-api` :)

at the moment i'm maintaining it and fixing bugs as needed, but i'm putting all active development in the new library `@vladmandic/human` instead as `face-api` is architecturally quite old  

more specifically, method i've implemented in face-api is older version that relies on [simple angle calculation](https://github.com/vladmandic/face-api/blob/a433fc06813142287faf4b20c26853990cfa2fbe/src/factories/WithFaceLandmarks.ts#L25-L58) between vector lines:

i have a newer way to calculate angles using rotation matrix which i've implemented in `@vladmandic/human`: [rotation matrix](https://github.com/vladmandic/human/blob/1b4376f7da95e916f3cca64cddab4060aa8c876a/src/face/angles.ts#L30)

**Comment by TheSohaibAhmed** [comment]
I'm not sure how to contribute to it, but I went ahead and fixed it (I think; fingers crossed!!). Here's codesandbox link: 
https://j6q0jb.csb.app/

Specifically, I went and selected specific points and created the right angles for it. It's still an approximate and I can refine it for sure, but it certainly looks more accurate =D

**Comment by vladmandic** [comment]
its looks pretty good to me...
instead of me copying and pasting the code, its best if you contribute directly:

- create fork on github  
  button top-right)  
- checkout you fork  
  `git clone ...`  
- install dev dependencies  
  `npm install --production=false`  
- make code changes on your local system  
  test as needed  
- make sure code passes lint and style check  
  `npm run lint`  
- make sure code builds cleanly  
  `npm run build`  
- commit changes back to your github fork  
  make sure you commit only files relevant to this code  
  so not things like your updated `package.json` or whatever  
- on github, create new pull request  
  select original branch as source and your branch as target  
  github automatically creates merge request  
  add notes as needed  
- then its up to me to review pull request, approve it and merge it

**Comment by vladmandic** [comment]
thanks for the pr #130 - overall looks pretty good, i've left some minor comments before the merge.

**Comment by TheSohaibAhmed** [comment]
^Woot! Yep -- I'm glad this got sorted out, and I responded to those comments too! :D

**Comment by vladmandic** [comment]
pr is merged and version 1.7.6 is published  
(in theory its a breaking change due to switch from radians to degrees, but i didn't think it deserved a major version bump)
