### ISSUE TITLE
How to use faceapi in nodejs with tfjs-backend-cpu?

### ISSUE THREAD

**Issue by zczcyc0201** [vladmandic/face-api#141]
Dear author, hello, i want to use your face-api in nodejs with tfjs-backend-cpu, i don't want to install tfjs-node, it's too large,

example:

const tfjs = require('@tensorflow/tfjs');
const faceapi = require('@vladmandic/face-api/dist/face-api.js');

I got this error:

TypeError: this.util.TextEncoder is not a constructor

Do you have any good suggestions? Thanks very much , very good project!

**Comment by vladmandic** [comment]
that's why there are different versions in `/dist` - you're loading browser package and that doesn't work in node.  

also, if you cannot or don't want to use `tfjs-node`, i **strongly** suggest to use `wasm` backend  
its 100x faster than `cpu` backend (which is not supported for anything but testing).  

for example, see <https://github.com/vladmandic/face-api/blob/master/demo/node-wasm.js>

but...if you really want, you can - to use `tfjs-backend-cpu`, simply remove `tfjs-backend-wasm` from demo and set backend to `cpu`.

**Comment by zczcyc0201** [comment]
Thank you very much for your help. I solved my problem!

**Comment by zczcyc0201** [comment]
One more question , when I use tfjs-wasm , a lot of memory is used , about 500m used when i run the face detector, if i set 

await tfjs.setBackend('cpu');

Even the same usage scenario, same images, it uses only 80m memory,

do you know why?

**Comment by vladmandic** [comment]
quick profiling:

```json
process start:   { rss:  87277568, heapUsed: 27744928, external:   1413911, arrayBuffers:    41994 }
wasm loaded:     { rss: 119750656, heapUsed: 25891488, external:  20853392, arrayBuffers:  1256400 }
models loaded:   { rss: 341614592, heapUsed: 37398240, external: 185780774, arrayBuffers: 10339174 }
detection run:   { rss: 519032832, heapUsed: 35881064, external: 271229754, arrayBuffers: 10198138 }
```

so `heap` usage grows and becomes stable when **gc** kicks in, but external usage (objects managed by **c++** code inside **wasm** module) grows a lot.
`rss` is `heap` + `external` + `buffers` plus process overhead.  
not only that, but due to how **wasm** works, `rss` is double `external` every time memory snapshot is is taken.

i took a quick look how it works internaly and it seems that for *anything*, **wasm** module currently tries to allocate in *256kb chunks*.  
this avoids memory fragmentation, but it means that any buffer will take a lot of memory.  
and additionally, **tfjs** -> **wasm** interaction is such that it only calls **wasm** memory dispose explicitly when it decides to, there is no auto-deallocation.  
meaning, it will try to keep as much in memory and only deallocate when it needs to - thus leading to what seems an always growing process, but it should stabilize once memory system memory is used.  

this threshold can be tuned for **webgl** backend, but i don't see a way to tune it for **wasm** backend.

not much i can do here as i stopped compiling my own wasm binaries (i used to in the past),  
so if anything this should be asked in <https://github.com/tensorflow/tfjs> repo.

**Comment by vladmandic** [comment]
how are you measuring memory usage?

if i compare `cpu` to `wasm` backends, difference is not huge:

```js
CPU:  { rss: 346742784, heapTotal: 61120512, heapUsed: 32789072, external: 111902914, arrayBuffers: 100428394 }
WASM: { rss: 497676288, heapTotal: 60334080, heapUsed: 35357856, external: 269790206, arrayBuffers: 10196390 }
```

wasm uses more `external` memory while `cpu` uses more buffers - both make total sense. at the end, its not a huge difference.

and if i try to limit js heap space allocation which triggers more aggresive garbage collection by v8 engine inside nodejs, heap memory usage goes down a little bit but the rest is pretty constant

```js
CPU: { rss: 325632000, heapTotal: 42246144, heapUsed: 26836512, external: 112103618, arrayBuffers: 100629098 }
WASM: { rss: 462467072, heapTotal: 34119680, heapUsed: 28830160, external: 271162929, arrayBuffers: 10196889 }
```

also, running with 100 iterations results in `extrernal` memory growth due to internal buffering, but it stabilizes relatively early and there is no leak.
