### ISSUE TITLE
Error: Based on the provided shape, [1,1,16,32], the tensor should have 512 values but has 48

### ISSUE THREAD

**Issue by ApexcupDeveloper** [vladmandic/face-api#170]
**Issue Description**
Error: Based on the provided shape, [1,1,16,32], the tensor should have 512 values but has 48

The library works as well on localhost but in production, I am getting above error when loading models.
I tried everything from google/stackoverflow but nothing works.

**Environment
"react": "^18.0.0",
 "@vladmandic/face-api": "^1.7.12",
 
 
![Screenshot 2023-06-20 at 04 05 13](https://github.com/vladmandic/face-api/assets/57320815/c6676bf4-a637-46a7-991d-e0aa30579509)

**Comment by vladmandic** [comment]
this tells me nothing.
1. deploy with non-minimized library backtrace can be read - this is currently pointless
2. include longer backtrace, not just final error meesage - i need to see what leads to this
3. check browser inspector network tab if model are actually served correctly and with correct mimetype (not just available, but also check if the type is correct, i've seen cases where web servers serve models as text instead of binary)

but at the end, if it works locally and not in production - its clearly a deployment issue - so what is different between the two?

**Comment by vladmandic** [comment]
no information provided, closing.
