### ISSUE TITLE
node got Error: Size(1048576) must match the product of shape 512,512,3

### ISSUE THREAD

**Issue by thapecroth** [vladmandic/face-api#30]
Using the code from nodejs example.  I send the base64 image from the client. using canvas.toDataUrl(); then on nodejs I use the following code to transform base64 to jpg then faceApi.
Note that using the normal jpg from internet the lib is working as expected. However, i download some img.jpg and inspect I can't find any difference.

`        
        const content = message.value.toString().replace(/^data:image\/png;base64,/, "");
        await fsp.writeFile('./img.jpg', content, 'base64')
        const rezied = await sharp('./img.jpg')
        .rotate()
        .resize(400,400)
        .toBuffer()
        await fsp.writeFile('./img.jpg',rezied)
        const tensor = await image('./img.jpg');
      
          const res = await faceapi
          .detectAllFaces(tensor, optionsSSDMobileNet)
          .withFaceLandmarks()
          .withFaceExpressions()
          .withFaceDescriptors()
          .withAgeAndGender();
    
        //   const faceMatcher = new faceapi.FaceMatcher(res)
          console.log('res:',res)
`
Here is the error code

            throw Error("Size(" + size + ") must match the product of shape " + shape);
                  ^
          Error: Size(1048576) must match the product of shape 512,512,3
              at util.inferFromImplicitShape (/home/thape/faceApi/node_modules/@tensorflow/tfjs-core/src/util_base.ts:317:13)
              at forward (/home/thape/faceApi/node_modules/@tensorflow/tfjs-core/src/ops/reshape.ts:64:13)
              at /home/thape/faceApi/node_modules/@tensorflow/tfjs-core/src/engine.ts:625:31
              at /home/thape/faceApi/node_modules/@tensorflow/tfjs-core/src/engine.ts:433:20
              at Engine.scopedRun (/home/thape/faceApi/node_modules/@tensorflow/tfjs-core/src/engine.ts:444:19)
              at Engine.tidy (/home/thape/faceApi/node_modules/@tensorflow/tfjs-core/src/engine.ts:431:17)
              at kernelFunc (/home/thape/faceApi/node_modules/@tensorflow/tfjs-core/src/engine.ts:625:20)
              at /home/thape/faceApi/node_modules/@tensorflow/tfjs-core/src/engine.ts:639:23
              at Engine.scopedRun (/home/thape/faceApi/node_modules/@tensorflow/tfjs-core/src/engine.ts:444:19)
    at Engine.runKernelFunc (/home/thape/faceApi/node_modules/@tensorflow/tfjs-core/src/engine.ts:636:10)

**Comment by vladmandic** [comment]
from a first look, it seems that result of your picture manipulation is RGBA image, not RGB (4 channels instead of 3).
is you pass image to tensorflow, it actually does the job of stripping extra channel. but if you create tensor manually, you have to do it yourself.  

take a look at conversation i had in <https://github.com/tensorflow/tfjs/issues/4227#issuecomment-728342644> for example.

**Comment by thapecroth** [comment]
Hi Vladmandic, 
Thank you for your insightful information. I add to change the transformed image with the following code.
        `const rezied = await sharp('./img.jpg')
        .rotate()
        .removeAlpha()
        .resize(400,400)
        .toBuffer()
        await fsp.writeFile('./img.jpg',rezied)`
and it's work. By the way, do you know the better way to process the base64 image without saving it to file first? it seem to be inefficient.

**Comment by vladmandic** [comment]
I've never used `sharp` library, but if return of `toBuffer` is actual buffer then you could create `ImageData` from it and pass that directly to `FaceAPI`.  
Something like (this is not tested, this is just an example):

```js
const b64 = message.value.toString().replace(/^data:image/png;base64,/, "");
const data = new Buffer(atob(b64));
const width = 400;
const height = 400;
const buffer = await sharp(data)
      .rotate()
      .removeAlpha()
      .resize(width, height)
      .toBuffer();
const image = new ImageData(new Uint8ClampedArray(buffer), width, height);
const res = await faceapi
      .detectAllFaces(buffer, optionsSSDMobileNet)
      .withFaceLandmarks()
      .withFaceExpressions()
      .withFaceDescriptors()
      .withAgeAndGender();
```

On the other hand, do you have to canvas to base64 to start with?  
If your web server accepts binary data, send canvas `ImageData` buffer directly which uses less bandwidth as well as skips encoding/decoding so it's faster.  

Something like:

```js
const ctx = canvas.getContext('2d');
const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
const buffer = imageData.data.buffer;  // ArrayBuffer
```

Only issue is you need to encode image width and height as well since buffer in this case does have any info on what's inside it.

**Comment by vladmandic** [comment]
i'm closing the issue as resolved...
