### ISSUE TITLE
WASM in web worker

### ISSUE THREAD

**Issue by HemantKumar01** [vladmandic/face-api#32]
i am using face-api.js and it workes great using wasm backend.
however when trying to do
```
faceapi.tf.setWasmPaths(
    "../node_modules/@tensorflow/tfjs-backend-wasm/dist/"
  );
  await faceapi.tf.setBackend("wasm");
```
results in an error 
```
Uncaught error: initialization of  backend wasm failed
```
and when i try to set backend to cpu, it shows-
```
 SSDMOBIlENETV1 : load model before inference
```
i am using a simple demo as shown in examples but in worker.

**Comment by vladmandic** [comment]
can you share your actual demo?

**Comment by HemantKumar01** [comment]
Here it is (i have just rearranged the code)-
```
if ("function" === typeof importScripts) {
  importScripts("face-api/face-api.js");
}

//window = self;

self.onmessage = async (e) => {
  console.log("from worker", e.data);
  await faceapi.tf.setWasmPaths(
    "../node_modules/@tensorflow/tfjs-backend-wasm/dist/"
  );
  await faceapi.tf.setBackend("wasm");
  console.log("wasm init complete")
  await loadModels;
  var tensor = faceapi.tf.browser.fromPixels(e.data)
  var data = await getFaceData(tensor);
  postMessage(data);
};

async function loadModels() {
  try {
    //await faceapi.tf.ready()
    console.log("loading face-api.js models");
    var time1 = new Date().getTime();
    await faceapi.nets.ssdMobilenetv1.loadFromDisk(path.join(__dirname, 'face-api/models'));
    await faceapi.nets.faceLandmark68Net.loadFromUri("./face-api/models");
    await faceapi.nets.faceExpressionNet.loadFromUri("./face-api/models");
    await faceapi.nets.faceRecognitionNet.loadFromUri("./face-api/models");
    console.log(
      `all face-api.js models loaded in: ${new Date().getTime() - time1} ms`
    );
    Promise.resolve();
  } catch (e) {
    console.log(`error in loading face-api models:\n ${e.name} : ${e.message}`);
    Promise.reject()
  }
}

async function getFaceData(image) {
  //faceapi.env.monkeyPatch({ Canvas, Image });
  try {
    // await faceapi.tf.ready()
    var time1 = new Date().getTime();
    //const image = await faceapi.fetchImage(imgUrl);
    //const canvas = faceapi.createCanvasFromMedia(image);
    const detection = await faceapi
      .detectAllFaces(image)
      .withFaceLandmarks()
      .withFaceExpressions()
      .withFaceDescriptors();
    console.log("detection took", new Date().getTime() - time1);
    //console.log(detection);
    const dimensions = {
      width: image.width,
      height: image.height,
    };

    const resizedDimensions = faceapi.resizeResults(detection, dimensions);
    console.log(resizedDimensions);
    return detection;
    //document.body.appendChild(canvas);
    //faceapi.draw.drawDetections(canvas, resizedDimensions);
    //faceapi.draw.drawFaceExpressions(canvas, resizedDimensions);
  } catch (error) {
    return `error while using image with face-api\n ${error.name} : ${error.message}`;
  }
}
```

**Comment by vladmandic** [comment]
error `SSDMOBIlENETV1 : load model before inference` is because:
```await faceapi.nets.ssdMobilenetv1.loadFromDisk(path.join(__dirname, 'face-api/models'));```
which is a method used in nodejs environments, not browser. all other models you're loading using `loadFromUri` except this one.

but on the webworker error, this seems to be worker-side of the code - i don't know how worker is initialized or even what gets loaded by `importScripts("face-api/face-api.js");`. nor do i know what's the type of `e.data` passed to worker, all i see you cast it tensor using `fromPixels` method. but loading models from inside `onmessage` event does look strange.

also, while debugging it's helpful to remove try/catch blocks to see actual errors as they happen.

it would be helpful if you can post entire project (either a link to git repository or all required files uploaded to gist) - i'll definitely take a look.

**Comment by vladmandic** [comment]
nevermind, i wrote a test app myself just do double-check - no luck.  

this is not related to **wasm** at all, `face-api` simply uses **DOM** objects extensively and **DOM** is not available inside web worker.
as such, `face-api` is not and will not be compatible with web workers. sorry. there is simply too much work to make it compatible with web workers.

may i suggest you try out my newer library (which i wrote after i've ported `face-api` and seen how many limitations it has)?
<https://github.com/vladmandic/human>
it is tested & functional with web workers.

i've changed the subject line to reflect issue with web workers in general and closing this issue as will-not-fix.

**Comment by HemantKumar01** [comment]
I have already tried `loadFromUri` which is giving the same error when backend set to cpu. 
`importScripts(...)` simply loads the face-api.js
e.data is just some image data.

The library human is great. I just wanted to use worker to reduce processing time. So my question is, is the other library human faster to make realtime on non gpu computers? Please reply as i needed this for a school project. Thanks in advance

**Comment by vladmandic** [comment]
I've mentioned `loadFromDisk()` as inorrect usage for browser environments, but it has nothing to do with web workers.  
simply put, `face-api` cannot work with web workers at all (CPU, WebGL, WASM, doesn't matter) as it heavily relies on DOM objects which are not available from within workers.  

Regarding `Human` library, yes it's faster than `face-api`. But it depends which models are enabled. And with WASM, the input resolution also matters a lot (since WASM does not have GPU accelerated pixel copy).
For maximum performance, disable all models you don't need. Also, may try to use `front` version of face detector as it's lower-resolution, but faster than `back` version. And limit the input image resolution.

The browser demo that comes with `Human` already has selectable option to enable web worker on/off.
