### ISSUE TITLE
Information about models used by FaceAPI

### ISSUE THREAD

**Issue by pabloegpf1** [vladmandic/face-api#35]
Hi!

For academic purposes I would need to get more information about some models (Tiny Face Detector, Face Recognizer Net and Face Landmark Model). 

Is there any documentation (papers, benchmarks...) that I could check out? Who developed and trained these models?

Thanks!

**Comment by vladmandic** [comment]
since i've only ported and modernized face-api library and original author is no longer available, i have limited info on sources of the models used.  

for example, i believe original tiny face detector comes from this paper: <https://arxiv.org/abs/1612.04402> and implementation comes from <https://github.com/justadudewhohacks/tfjs-tiny-yolov2>  

for libraries i write, i always include credits for models used (e.g., take a look at <https://github.com/vladmandic/human>).

**Comment by pabloegpf1** [comment]
Thanks for the information, I will try to figure out more about the rest of the models and let you know. 

Best!
