### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by deylyn** [vladmandic/face-api#78]
warning  in ./node_modules/@vladmandic/face-api/dist/face-api.esm.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

how am i importing it->import * as faceapi from "@vladmandic/face-api/dist/face-api.esm.js";

quasar 1.9.6 framework de vue 2
node 12.18.0
face api 1.5.7

**Comment by vladmandic** [comment]
I'm not familiar with `quasar 1.9.6` or `vue 2`, but most likely its the same issue as with any SSR (server-side-rendering) which means you need to configure your packer to correctly link for the web (which means marking some items as external)  

(I'm guessing that since `import * as faceapi from "@vladmandic/face-api/dist/face-api.esm.js` is not a native NodeJS syntax which means something else is parsing the code - and a quick google for quasar confirmed that)

Again, I don't know which packer your environment uses, but for example `Next.JS` uses `WebPack` and some of the suggestions can be found here: <https://github.com/vladmandic/face-api/issues/65#issuecomment-911956356>

At the very minimum, increase verbosity of your environment as this message:
> Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
Is not informative at all. Where? Which dependency?

All-in-all, this is up to `quasar` configuration.
And for hints see past issues regarding `NextJS` since that is most common such framework.
